// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNWN822yuEy8koY89MBmQdltbgj4URcbo',
    appId: '1:561345133345:web:3a10878724ae339ece5c60',
    messagingSenderId: '561345133345',
    projectId: 'graduation-project-f4664',
    authDomain: 'graduation-project-f4664.firebaseapp.com',
    storageBucket: 'graduation-project-f4664.appspot.com',
    measurementId: 'G-TQN7D3XE4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxXfJabUH0CnFmsAG_MadE2R8MHptPrcA',
    appId: '1:561345133345:android:3adde721f6f77765ce5c60',
    messagingSenderId: '561345133345',
    projectId: 'graduation-project-f4664',
    storageBucket: 'graduation-project-f4664.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBpsjyqhqDxVTWOQOrUnYqLHQhPEQ-43I',
    appId: '1:561345133345:ios:e10eb5751703280dce5c60',
    messagingSenderId: '561345133345',
    projectId: 'graduation-project-f4664',
    storageBucket: 'graduation-project-f4664.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBpsjyqhqDxVTWOQOrUnYqLHQhPEQ-43I',
    appId: '1:561345133345:ios:f301cfa982ffe2eace5c60',
    messagingSenderId: '561345133345',
    projectId: 'graduation-project-f4664',
    storageBucket: 'graduation-project-f4664.appspot.com',
    iosBundleId: 'com.example.graduationProject.RunnerTests',
  );
}
